<?xml version="1.0"?>
<package format="2">
  <name>hd_map_pkg</name>
  <version>0.0.0</version>
  <description>Versioned static HD map products, conversion and validation.</description>
  <maintainer email="simonpaik04@gmail.com">Team Stier</maintainer>
  <license>TODO</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>common_msgs_pkg</depend>
  <depend>geometry_msgs</depend>
  <depend>ros_architecture_pkg</depend>
  <depend>rospy</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-rospkg</exec_depend>
  <test_depend>python3-nose</test_depend>
  <export />
</package>
