<?xml version="1.0"?>
<package format="2">
  <name>localization_pkg</name>
  <version>0.1.0</version>
  <description>GPS, IMU, and vehicle-twist dual-EKF localization configuration.</description>

  <maintainer email="maintainer@example.com">MOLIT Team</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>geographiclib</depend>
  <depend>nav_msgs</depend>
  <depend>robot_localization</depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <test_depend>python3-yaml</test_depend>
  <test_depend>rosgraph</test_depend>
  <test_depend>rosnode</test_depend>
  <test_depend>rosservice</test_depend>
  <test_depend>rostest</test_depend>

  <export/>
</package>
