<?xml version="1.0"?>
<package format="2">
  <name>path_planning_pkg</name>
  <version>0.0.0</version>
  <description>Behavior planning and feasible time-parameterized local trajectory generation.</description>
  <maintainer email="simonpaik04@gmail.com">Team Stier</maintainer>
  <license>TODO</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>common_msgs_pkg</depend>
  <depend>ros_architecture_pkg</depend>
  <export />
</package>
