#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""IMU UDP Bridge 노드 실행 진입점. 로직은 morai_interface_pkg.imu_node에 있다."""

from morai_interface_pkg.imu_node import main

if __name__ == "__main__":
    main()

